### ISSUE TITLE
[Milestone] Initial publishing

### ISSUE THREAD

**Issue by Ailrun** [freetextjs/freetextjs#1]
**To publish the package :package:, we should**

- [ ] have basic document
- [ ] have test settings
- [ ] CI settings

**and we may**

- [ ] have live example
